[package]
name = "time_steward"
version = "0.1.0"
authors = ["Eli Dupree <vcs@elidupree.com>"]

[dependencies]
rand = "0.3"
nalgebra = "0.8.2"
polynomial = "0.0.5" 
roots = "0.0.2"
glium = "0.15"
serde = "0.8"
serde_macros = "0.8"
serde_json = "0.8"
quickcheck = "0.3"
quickcheck_macros = "0.2"
bincode = "0.6"
